### ISSUE TITLE
是否会有重复下载和下载超出磁盘剩余空间大小的种子的问题？

### ISSUE THREAD

**Issue by PairZhu** [liichao/MTAutoFreeBT#2]
代码中似乎没看到从rss订阅链接中去除旧种子或者检查qb是否已有对应种子的代码（即便重复添加会添加失败然后报错，但是一些旧种也没太大下载的必要，如果之前手动删除了是不是会自动下回来），也没看到预先检测种子大小的代码

**Comment by liichao** [comment]
逻辑规则比较简单，获取rss链接中的种子是否是free、2xfree 当符合条件时，获取种子链接，此时读取qb获取到的剩余空间大小
大于配置值时，开始下载


在 2024年7月29日 at 00:26:59, Wenhao Zhu ***@***.***) 写到:

**Comment by PairZhu** [comment]
已提交PR，新提交的PR增加了以上所提到的功能
